// Code generated by command: go run main.go -component=zigzag -out=../../zigzag_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func zigzagEncodeSIMDAsm(buf *uint32, n int)
// Requires: SSE2
TEXT ·zigzagEncodeSIMDAsm(SB), NOSPLIT, $0-16
	MOVQ buf+0(FP), AX
	MOVQ n+8(FP), CX
	MOVQ CX, DX
	ANDQ $0xfffffffc, DX
	ANDQ $0x03, CX

zigzag_encode_unroll_loop:
	CMPQ  DX, $0x10
	JL    zigzag_encode_unroll_done
	MOVO  (AX), X0
	MOVO  16(AX), X2
	MOVO  32(AX), X4
	MOVO  48(AX), X6
	MOVO  X0, X1
	PSRAL $0x1f, X1
	MOVO  X2, X3
	PSRAL $0x1f, X3
	MOVO  X4, X5
	PSRAL $0x1f, X5
	MOVO  X6, X7
	PSRAL $0x1f, X7
	PSLLL $0x01, X0
	PSLLL $0x01, X2
	PSLLL $0x01, X4
	PSLLL $0x01, X6
	PXOR  X1, X0
	PXOR  X3, X2
	PXOR  X5, X4
	PXOR  X7, X6
	MOVO  X0, (AX)
	MOVO  X2, 16(AX)
	MOVO  X4, 32(AX)
	MOVO  X6, 48(AX)
	ADDQ  $0x40, AX
	SUBQ  $0x10, DX
	JMP   zigzag_encode_unroll_loop

zigzag_encode_unroll_done:
zigzag_encode_vec_loop:
	CMPQ  DX, $0x00
	JE    zigzag_encode_vec_done
	MOVO  (AX), X0
	MOVO  X0, X1
	PSRAL $0x1f, X1
	MOVO  X0, X0
	PSLLL $0x01, X0
	PXOR  X1, X0
	MOVO  X0, (AX)
	ADDQ  $0x10, AX
	SUBQ  $0x04, DX
	JMP   zigzag_encode_vec_loop

zigzag_encode_vec_done:
zigzag_encode_tail_loop:
	CMPQ CX, $0x00
	JE   zigzag_encode_tail_done
	MOVL (AX), DX
	MOVL DX, BX
	SARL $0x1f, BX
	SHLL $0x01, DX
	XORL BX, DX
	MOVL DX, (AX)
	ADDQ $0x04, AX
	DECQ CX
	JMP  zigzag_encode_tail_loop

zigzag_encode_tail_done:
	RET

// func zigzagDecodeSIMDAsm(buf *uint32, n int)
// Requires: SSE2
TEXT ·zigzagDecodeSIMDAsm(SB), NOSPLIT, $0-16
	MOVQ buf+0(FP), AX
	MOVQ n+8(FP), CX
	MOVQ CX, DX
	ANDQ $0xfffffffc, DX
	ANDQ $0x03, CX

zigzag_decode_unroll_loop:
	CMPQ  DX, $0x10
	JL    zigzag_decode_unroll_done
	MOVO  (AX), X0
	MOVO  16(AX), X2
	MOVO  32(AX), X4
	MOVO  48(AX), X6
	MOVO  X0, X1
	PSLLL $0x1f, X1
	PSRAL $0x1f, X1
	MOVO  X2, X3
	PSLLL $0x1f, X3
	PSRAL $0x1f, X3
	MOVO  X4, X5
	PSLLL $0x1f, X5
	PSRAL $0x1f, X5
	MOVO  X6, X7
	PSLLL $0x1f, X7
	PSRAL $0x1f, X7
	PSRLL $0x01, X0
	PSRLL $0x01, X2
	PSRLL $0x01, X4
	PSRLL $0x01, X6
	PXOR  X1, X0
	PXOR  X3, X2
	PXOR  X5, X4
	PXOR  X7, X6
	MOVO  X0, (AX)
	MOVO  X2, 16(AX)
	MOVO  X4, 32(AX)
	MOVO  X6, 48(AX)
	ADDQ  $0x40, AX
	SUBQ  $0x10, DX
	JMP   zigzag_decode_unroll_loop

zigzag_decode_unroll_done:
zigzag_decode_vec_loop:
	CMPQ  DX, $0x00
	JE    zigzag_decode_vec_done
	MOVO  (AX), X0
	MOVO  X0, X1
	PSLLL $0x1f, X1
	PSRAL $0x1f, X1
	MOVO  X0, X0
	PSRLL $0x01, X0
	PXOR  X1, X0
	MOVO  X0, (AX)
	ADDQ  $0x10, AX
	SUBQ  $0x04, DX
	JMP   zigzag_decode_vec_loop

zigzag_decode_vec_done:
zigzag_decode_tail_loop:
	CMPQ CX, $0x00
	JE   zigzag_decode_tail_done
	MOVL (AX), DX
	MOVL DX, BX
	ANDL $0x01, BX
	NEGL BX
	SHRL $0x01, DX
	XORL BX, DX
	MOVL DX, (AX)
	ADDQ $0x04, AX
	DECQ CX
	JMP  zigzag_decode_tail_loop

zigzag_decode_tail_done:
	RET
